server:
  port: 8097

spring:
  application:
    name: SecurePaste
  
  # Database configuration
  datasource:
    url: jdbc:h2:mem:pastebin;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  # H2 Console (for development)
  h2:
    console:
      enabled: true
      path: /h2-console

  # Security configuration
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

# Logging configuration
logging:
  level:
    com.securepaste: INFO
    org.springframework.security: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# OpenAPI documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  show-actuator: true

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

---
# Production profile
spring:
  config:
    activate:
      on-profile: production
      
  datasource:
    url: jdbc:postgresql://localhost:5432/pastebin
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:pastebin}
    password: ${DB_PASSWORD:pastebin}
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    
  h2:
    console:
      enabled: false

server:
  port: ${PORT:8080}

logging:
  level:
    com.securepaste: INFO
    org.springframework.security: WARN
  file:
    name: logs/securepaste.log

---
# Docker profile
spring:
  config:
    activate:
      on-profile: docker
      
  datasource:
    url: jdbc:postgresql://postgres:5432/pastebin
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:pastebin}
    password: ${DB_PASSWORD:pastebin}
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8080