apiVersion: v1
kind: Namespace
metadata:
  name: securepaste
  labels:
    app: securepaste
    version: "1.0.0"
---
# Resource quotas for the namespace
apiVersion: v1
kind: ResourceQuota
metadata:
  name: securepaste-quota
  namespace: securepaste
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    persistentvolumeclaims: "3"
    pods: "10"
    services: "5"
---
# Network policy for security
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: securepaste-network-policy
  namespace: securepaste
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    - namespaceSelector:
        matchLabels:
          name: securepaste
    ports:
    - protocol: TCP
      port: 8080
    - protocol: TCP
      port: 5432
  egress:
  - {}  # Allow all egress for now, can be restricted further